// src/data/courses.js

const courses = [
    { id: 1, title: 'Object Oriented Programming(C&C++)', category: 'CS/IT',image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg", description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity", 

 },
    { id: 2, title: 'Database management system', category: 'CS/IT',image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg" ,description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity. ",},
    { id: 3, title: 'Programming in Java', category: 'CS/IT',image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg",description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity. ", },
    { id: 4, title: 'Data structures and Algorithm', category: 'CS/IT' ,image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg",description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity.."},
    
    
    { id: 5, title: 'Analog Communications', category: 'ECE' ,image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg",description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity. ",},
    { id: 6, title: 'Machine Learning with Python', category: 'ECE',image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg",description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity. ", },
    { id: 8, title: 'Digital Electronics', category: 'ECE',image:"https://thumbs.dreamstime.com/b/oops-sticky-note-yellow-pinned-red-push-pin-cork-board-92680037.jpg",description: "Object-Oriented Programming (OOP) is a programming paradigm that uses objects to design applications and computer programs. The core principles of OOP are encapsulation, abstraction, inheritance, and polymorphism. Encapsulation bundles data and methods that operate on the data within one unit, such as a class, and restricts direct access to some of the object's components, ensuring data integrity.", },
  ];
  
  export default courses;
  